# Generated by Django 2.2.7 on 2021-04-28 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('silk', '0008_sqlquery_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
